name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "qx-wiki"
database_id = "bbba9310-f06e-4378-a19f-14dd570da6ba"
